version: '3'
services:
  s3:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./storage/minio:/data

    environment:
      MINIO_ACCESS_KEY: 123456789
      MINIO_SECRET_KEY: 123456789
      MINIO_ROOT_USER: 123456789
      MINIO_ROOT_PASSWORD: 123456789

    command: server --console-address :9001 /data

  apppy:
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
        - s3
